[workspace]

members = [
  "fvr_engine",
  "fvr_engine-atlas",
  "fvr_engine-client",
  "fvr_engine-core",
  "fvr_engine-parser",
  "fvr_engine-server",
]

default-members = [
  "fvr_engine"
]

[profile.release]
debug = true