[package]
name = "fvr_engine-parser"
version = "0.1.0"
authors = ["Jacob Adkins <jacobpadkins@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
criterion = "0.3.4"
nom = "6.1.2"

[[bench]]
name = "rich_text_benchmark"
harness = false