[package]
name = "fvr_engine-renderer"
version = "0.1.0"
authors = ["Jacob Adkins <jacobpadkins@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"

[dependencies.sdl2]
version = "0.34.2"
default-features = false
features = ["image"]