[package]
name = "fvr_engine"
version = "0.1.0"
authors = ["Jacob Adkins <jacobpadkins@gmail.com>"]
edition = "2018"

[dependencies]
fvr_engine-parser = { path = "../fvr_engine-parser", version = "0.1.0" }
fvr_engine-renderer = { path = "../fvr_engine-renderer", version = "0.1.0" }
anyhow = "1.0.38"
bracket-lib = "0.8.1"
specs = "0.16.1"
specs-derive = "0.4.1"

[dependencies.sdl2]
version = "0.34.2"
default-features = false
features = ["image"]