[package]
name = "fvr_engine-atlas_generator"
version = "0.1.0"
authors = ["Jacob Adkins <jacobpadkins@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
clap = "2.33.3"
hashbrown = "0.9.1"
image = "0.23.13"
serde = "1.0.123"
serde_derive = "1.0.123"
toml = "0.5.8"
xml-rs = "0.8.3"